#!/bin/sh
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2007-2018 ANSSI. All Rights Reserved.
#######################################################################
# CLIP install tool
# Author: EADS Defence & Security
#######################################################################

/usr/bin/clip_install -d rm -p apps
